apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-example-arm-template
spec:
  environments:
  - name: qa
    build:
      from: master
  components:
  - name: "api"
    src: "./todoapi"
    ports:
    - name: http
      port: 3000
    public: true
    secrets:
      - AZURE_STORAGE_CONNECTION_STRING
    environmentConfig:
    - environment: qa
      horizontalScaling:
        minReplicas: 1
        maxReplicas: 2
      monitoring: true
      resources:
        requests:
          memory: "100M"
          cpu: "50m"
        limits:
          memory: "250M"
          cpu: "500m"
      variables:
        PIPELINE_IMG_TAG: "master-latest"