name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: deploy-arm-template
      env:
        RESOURCE_GROUP: db-api-radix-qa
        DEPLOY_NAME: azuredeploy
      run: |
        az group deployment create -g $RESOURCE_GROUP -n $DEPLOY_NAME --template-file ./arm-templates/azuredeploy.json --parameters ./arm-templates/azuredeploy.parameters.json
      
