name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: deploy-api  
      env:
        ACCESS_TOKEN: ${{ secrets.K8S_CREDENTIALS }}
        APP_NAME: radix-example-arm-template
      run: |    
        BRANCH=${GITHUB_REF##*/}    
        curl -v -f -X POST "https://server-radix-api-prod.playground.radix.equinor.com/api/v1/applications/${APP_NAME}/pipelines/build-deploy" -H "accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer ${ACCESS_TOKEN}" -d "{\"branch\":\"${BRANCH}\", \"commitID\":\"${GITHUB_SHA}\"}"
    - name: deploy-arm-template
      env:
        RESOURCE_GROUP: db-api-radix-qa
        DEPLOY_NAME: azuredeploy
      run: |
        az group deployment create -g $RESOURCE_GROUP -n $DEPLOY_NAME --template-file ./arm-templates/azuredeploy.json --parameters ./arm-templates/azuredeploy.parameters.json
    - name: set-api-secrets
      env:
        ACCESS_TOKEN: ${{ secrets.K8S_CREDENTIALS }}
        APP_NAME: radix-example-arm-template
        SECRET_NAME: AZURE_STORAGE_CONNECTION_STRING
        COMPONENT_NAME: api
        ENVIRONMENT: qa
      run: |
        CONNECTION_STRING=$(az group deployment show -g db-api-radix-qa -n azuredeploy --query properties.outputs.storageConnectionString.value)
        curl -v -f -X POST "https://server-radix-api-prod.playground.radix.equinor.com/api/v1/applications/${APP_NAME}/environments/${ENVIRONMENT}/components/${COMPONENT_NAME}/secrets/${SECRET_NAME}" -H "accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer ${ACCESS_TOKEN}" -d "{\"secretValue\":\"${CONNECTION_STRING}\"}"
