name: CI

on:
  push:
    branches:
      - master
      - release

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    env:
      APP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.K8S_CREDENTIALS }}
    steps:
      - uses: actions/checkout@v1
      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Get environment from branch
        id: getEnvironment
        uses: equinor/radix-github-actions@master
        with:
          args: >
            get-config branch-environment
            -b ${GITHUB_REF##*/}
      - name: Build and deploy API on Radix
        uses: equinor/radix-github-actions@master
        with:
          args: >
            build-deploy
            --cluster iknu-test-machine-user
            -b ${GITHUB_REF##*/}
            -f
      - name: Get instrumentation key and connection string
        id: getSecrets
        run: |
          RESOURCE_GROUP=db-api-radix-${{ steps.getEnvironment.outputs.result }}
          INSTRUMENTATIONKEY=$(az group deployment show -g ${RESOURCE_GROUP} -n azuredeploy --query properties.outputs.appInsightInstrumentationKey.value)
          CONNECTION_STRING=$(az group deployment show -g ${RESOURCE_GROUP} -n azuredeploy --query properties.outputs.storageConnectionString.value)

          echo ::set-output name=instrumentationKey::$(echo ${INSTRUMENTATIONKEY})
          echo ::set-output name=connectionString::$(echo ${CONNECTION_STRING})

          echo ::add-mask::${INSTRUMENTATIONKEY}
          echo ::add-mask::${CONNECTION_STRING}
      - name: Set instrumentation key as secret
        uses: equinor/radix-github-actions@master
        with:
          args: >
            set environment-secret
            --cluster iknu-test-machine-user
            -e ${{ steps.getEnvironment.outputs.result }}
            --component api
            -s APPINSIGHTS_INSTRUMENTATIONKEY
            -v '${{ steps.getSecrets.outputs.instrumentationKey }}'
      - name: Set connection string as secret
        uses: equinor/radix-github-actions@master
        with:
          args: >
            set environment-secret
            --cluster iknu-test-machine-user
            -e ${{ steps.getEnvironment.outputs.result }}
            --component api
            -s AZURE_STORAGE_CONNECTION_STRING
            -v '${{ steps.getSecrets.outputs.connectionString }}'
      - name: Run multiple CLI commands in one go
        run: |
          sh ./hack/install_radix_cli.sh
          echo 'Output from APPLICATIONS:'
          APPLICATIONS=$(./rx --token-environment --cluster iknu-test-machine-user list applications)

          echo ''
          echo ''
          echo ''

          echo 'Output from APPLICATIONS2:'
          APPLICATIONS2=$(./rx --token-environment --cluster iknu-test-machine-user list applications)
      - name: Is Radix CLI still installed
        run: |
          echo 'Output from APPLICATIONS:'
          APPLICATIONS=$(./rx --token-environment --cluster iknu-test-machine-user list applications)
