name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: deploy-arm-template
      env:
        RESOURCE_GROUP: db-api-radix-qa
        DEPLOY_NAME: azuredeploy
      run: |
        az group deployment create -g $RESOURCE_GROUP -n $DEPLOY_NAME --template-file ./arm-templates/azuredeploy.json --parameters ./arm-templates/azuredeploy.parameters.json
        ACCESS_TOKEN=$(az account get-access-token | jq -r '.accessToken')
        curl -X POST "http://api.radix.equinor.com/api/v1/applications/radix-example-arm-template/pipelines/build-deploy" -H "accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $ACCESS_TOKEN" -d "{ \"branch\": \"master\", \"commitID\": \"4faca8595c5283a9d0f17a623b9255a0d9866a2e\",}"

